// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebEFMVCDemo.Data;

#nullable disable

namespace WebEFMVCDemo.Migrations
{
    [DbContext(typeof(WebEFMVCDemoContext))]
    partial class WebEFMVCDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebEFMVCDemo.Models.Kontingent", b =>
                {
                    b.Property<int>("KontintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KontintId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("KontintId");

                    b.ToTable("Kontingents");

                    b.HasData(
                        new
                        {
                            KontintId = 1,
                            Name = "betalt"
                        },
                        new
                        {
                            KontintId = 2,
                            Name = "ikke betalt"
                        });
                });

            modelBuilder.Entity("WebEFMVCDemo.Models.Medlem", b =>
                {
                    b.Property<Guid>("Medlem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bosted")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Etternavn")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fodselsdato")
                        .HasColumnType("date");

                    b.Property<string>("Fornavn")
                        .HasColumnType("text");

                    b.Property<int>("KontintId")
                        .HasColumnType("integer");

                    b.Property<int?>("MobilTlf")
                        .HasColumnType("integer");

                    b.HasKey("Medlem_Id");

                    b.HasIndex("KontintId");

                    b.ToTable("Medlems");
                });

            modelBuilder.Entity("WebEFMVCDemo.Models.Medlem", b =>
                {
                    b.HasOne("WebEFMVCDemo.Models.Kontingent", "Kontingent")
                        .WithMany("Medlems")
                        .HasForeignKey("KontintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontingent");
                });

            modelBuilder.Entity("WebEFMVCDemo.Models.Kontingent", b =>
                {
                    b.Navigation("Medlems");
                });
#pragma warning restore 612, 618
        }
    }
}
