// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebMVCDemo.Data;

#nullable disable

namespace WebMVCDemo.Migrations
{
    [DbContext(typeof(WebMVCDemoContext))]
    partial class WebMVCDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("English_United States.1252)")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebMVCDemo.Models.Kontingent", b =>
                {
                    b.Property<int>("KontintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KontintId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("KontintId");

                    b.ToTable("Kontingent");
                });

            modelBuilder.Entity("WebMVCDemo.Models.Medlem", b =>
                {
                    b.Property<Guid>("Medlem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bosted")
                        .HasColumnType("text");

                    b.Property<int>("CurrentKontintId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fodselsdato")
                        .HasColumnType("date");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MobilTlf")
                        .HasColumnType("integer");

                    b.HasKey("Medlem_Id");

                    b.HasIndex("CurrentKontintId");

                    b.ToTable("Medlem");
                });

            modelBuilder.Entity("WebMVCDemo.Models.Medlem", b =>
                {
                    b.HasOne("WebMVCDemo.Models.Kontingent", "Kontingent")
                        .WithMany("Medlems")
                        .HasForeignKey("CurrentKontintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontingent");
                });

            modelBuilder.Entity("WebMVCDemo.Models.Kontingent", b =>
                {
                    b.Navigation("Medlems");
                });
#pragma warning restore 612, 618
        }
    }
}
